sudo: false
language: node_js
node_js:
  - '6'
  - '7'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
env:
  global:
    # EGG_PASSPORT_WEIBO_CLIENT_ID
    - secure: "OMk0jeug9eaOVT2c/578o/uqAjRvzF3jfIqk9qWw/6o/UB61EcNXSPswr/okbCzg4XWFnploFbiXQQHugbqZLy+GKqXBXZxKOXSsKgwFPmYFgSuFo3mINQCO3AT7rMDVIp2078pZ00Gn2eRTYf6i65YArrAiyKlLCzdOZ6NDGmLavvjylyKvf3Eb9qPqIDn+9pJkyEoSmhey5IEBZnj5A3PtIsaS6NZnfMsEGw3VcmxGtaK5rnhs9c5Ao/9fmMIaBAYdMfuMRZ3zHI1xXE5YWF9sowZMdWMJKVRT42AXJHOnJEONCImcosIIZsLh2bbtlGLNnceZLiJToZnui6vZYo2vbqGlx5c+vC6clH5/Qzxm7/InqeCBL5pKidgbQoKqgnMR1+qWnR8/rHsdR+J3gGPwYZ00z/k5GjnyWEnUrBOdJnCtUzbwpOKVUCzkvF3wpeEiEbDsY4+0IYj/gbUtggvEQvThs6OoBk1pF4jtUIQzXm2ISfzyBl81sGd552fVTDX403zZSC1sAffCnY9oC7kiY16uAFeUmkfEnhbYbMtw8LvgokM18A4lQWr9d087sxoG9OJT2My4HOHnHE5T5eMVxFfHy8d6sUiua4S/hIIwdyA5ylHpfNTH5bljHu25ZwqPgPxnFoLcgKxtPBG3GBxE8raW9wPCONjnY504jPA="
    # EGG_PASSPORT_WEIBO_CLIENT_SECRET
    - secure: "ai3+MAW4hL9No1FHt6eWtCpFLYVsLK6G4kybq9rgjIhlQ/jaDSyl1rqMgkDG+trjBgPEDYBdgtfXV5EEmoy7SairUZywElC99uKhyn/Tm08e7uQtjEfpfwZD1DYvD7C3HV1tkZ45AyvlMC/RmsBcBBTMJ04wDOKR6rQUeGfvxiKL9sHm7brg1SF0Zhm0qkvYqt1n3byKXlp98HtJBYAJ18K/jUCsy4QStD5ScALG+FjSU5B0kaT1GIKg4T0iRZSN0O8GD9NCCkigaqo3Tp7uhgB1qV4dmz04vDfb7UClwBwle/ig+9ijocBjMrATQfwd9Kty0bZB/35wDynCONfrERjl624sQrDQgb+q54Y1LgTL342M/AzqwqU5Eiuzy4O7bXr9boi0wZVPgkLPMIrUemrOtaQGrKoHEtahgf9NmUqHniz8rhWgL6RjAgGqgSynn18BWXvyK274xcIou01YtTcgQtMTLnoqv3BDZ+9cd9WlteGufXcBm3/Xv8BQRhmxgo9q5EecTd63n9g57hgn2FXDlHX3Kj5rmy+Bhfxs1obSSr1oBjchQQOf/bWhQEK9oAUAslpXPqdJt/BEtyGv7KLbDJgcGuqBse5i9Yi4A0T1Je+YYRhUaEUQUBnzPafJ4pN31j+pdiBUHbdm56sFVd8twL3+dsbZ4uNon6eStGw="
